version: '3.8'

services:
  db:
    container_name: spring_task_db
    ports:
      - "9090:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=spring_task_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    image: postgres:14
    restart: always