spring:
  application:
    name: SpringTask
  datasource:
    url: jdbc:postgresql://localhost:9090/spring_task_db
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration